### ISSUE TITLE
stdoutStream not visible

### ISSUE THREAD

**Issue by whirr** [crelies/ArgumentParserKit#1]
I want to call

`parser.printUsage(on: stdoutStream)`

but **stdoutStream** is **private** and not visible from out of the module, can be made **public**?

**Comment by crelies** [comment]
Hey @whirr ,

it's been a long time ago. In the last 6 months I was very busy with other things.

Now I took some time andI made `stdoutStream` and `stderrStream` public. Maybe you still need it ;)
